### PR TITLE
Texte de remplacement pas de prof ni salle

### PR DESCRIPTION
**Pull request by sivelswhy**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] You can **build successfully** the whole project with your changes locally
- [x] You use the coding conventions and the **naming conventions** of the project
- [x] You use **tabs** for indentation
- [x] You make sure that your PR is **not a duplicate**
- [x] This PR is **ready** to be reviewed and merged
- [x] This PR merges into the **`development`** branch or in the specific branch of the feature you want to merge into
- [x] There is no **`TODO`** in the code
- [x] There is no spelling or grammatical errors in the code
- [x] Details of the issue or feature are documented below
- [x] This PR is **not** a **breaking change** (e.g. changes that would cause existing functionality to change)

## Proposed changelog

| Français `fr` |
| --- |
| Ajout d'une condition si il n'y a pas de prof ni de salle dans l'ajout d'une journée au calendrier |

### Note
Before merging this PR, you will need the approval of at least one of the following people:
- @ecnivtwelve
- @lucas-luchack

So be patient ;)

### CODE REVIEW

**Comment by lucas-luchack** [comment]
Peux tu montrer dans quel cas cette PR est utile et ce que cela donne ?

**Review by lucas-luchack — CHANGES_REQUESTED** [review]
Peux tu modifier "prof" à "professeur" pour éviter le vocabulaire familier...

**Comment by sivelswhy** [comment]
C'est fait

**Review by lucas-luchack — APPROVED** [review]
Tout me semble bon 👀
Voir avec @ecnivtwelve s'il veut l'implémenter de cette façon 😉

**Comment by ecnivtwelve** [comment]
Je valide ! ✔️

**Pull request merged**
